//
//  StudentInformation.swift
//  OnTheMap
//
//  Created by Daniel Soutar on 13/09/2020.
//  Copyright © 2020 Daniel Soutar. All rights reserved.
//

import Foundation

struct StudentInformation : Codable {
    /** First name of the Student */
    var firstName: String
    /** Last name of the Student */
    var lastName: String
    /** Longitude of student location, in range (-90.0, 90.0) */
    var longitude: Double
    /** Latitude of student location, in range (-90.0, 90.0) */
    var latitude: Double
    /** Location string used for geocoding the student location (e.g. Buckingham Palace, London, UK) */
    var mapString: String
    /** URL provided by the student */
    var mediaURL: String
    /** Extra (optional) key used to uniquely identify a StudentLocation; this should be populated with corresponding Udacity account ID */
    var uniqueKey: String
    /** Auto-generated id/key generated by Udacity API which uniquely identifies a StudentLocation */
    var objectId: String
    /** Date when the student location was created */
    var createdAt: String
    /** Date when the student location was updated */
    var updatedAt: String
}
